# 工作流名称
name: CI & Deploy

# 触发条件：改为推送到所有分支时都触发
on:
  push:
    branches:
      - '**' # '**' 匹配所有分支

# 作业：定义两个作业，'test' 和 'deploy'
jobs:
  # 作业1：测试 (在所有分支上运行)
  test:
    # 运行环境：使用最新的 Ubuntu 虚拟机
    runs-on: ubuntu-latest

    # 步骤：定义测试作业的具体执行步骤
    steps:
      # 步骤 1: 检出代码
      - name: Checkout
        uses: actions/checkout@v4

      # 步骤 2: 设置 pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      # 步骤 3: 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      # 步骤 4: 安装依赖
      - name: Install dependencies
        run: pnpm install

      # 步骤 5: 运行测试
      # 如果测试失败，此作业将失败，并且 'deploy' 作业不会运行
      - name: Run tests
        run: pnpm test

  # 作业2：构建和部署 (仅在 main 分支上运行)
  deploy:
    # 使用 if 条件判断，只有当 git ref (引用) 是 main 分支时才执行此作业
    if: github.ref_name == 'main'

    # 添加 needs: test，确保测试作业成功后才开始部署
    needs: test

    # 作业环境：指定该作业在 GitHub Pages 的环境中运行
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # 运行环境
    runs-on: ubuntu-latest

    # 权限设置
    permissions:
      contents: read
      pages: write
      id-token: write

    # 步骤
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      # 注意：这里的 pnpm test 是可选的，因为 test 作业已经跑过了
      # 但保留它可以作为双重保险
      - name: Run tests
        run: pnpm test

      - name: Build project
        run: pnpm build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4